### ISSUE TITLE
NoneType Object is Not Subscriptable Error

### ISSUE THREAD

**Issue by vinayakmalik95** [trinodb/trino-python-client#483] opened 2024-09-13 07:17 UTC
### Expected behavior

When 

    def process(self, http_response) -> TrinoStatus:
        if not http_response.ok:
            self.raise_response_error(http_response)

        http_response.encoding = "utf-8"
        response = http_response.json()
        if "error" in response:
            raise self._process_error(response["error"], response.get("id"))

response is a dict so the logic is not correct over here, actually it should be 

### Actual behavior

if "error" in response: condition in client.py where error is None it gives 

Error: NoneType Object is Not Subscriptable Error

### Steps To Reproduce

This occur when I am trying to read via python client when activating data for Apache kyuubi where trinofrontendservice is hosted.

from trino.dbapi import connect
from trino.auth import BasicAuthentication
from trino import constants

user_name = "sample user"
api_key = "somekey"

conn = connect(
    source="constants.DEFAULT_SOURCE,
    host="192.168.68.82",
    port="7732",
    auth=BasicAuthentication(user_name, api_key),
    http_scheme="https",
)

cur = conn.cursor()
query = """SELECT * FROM catalog.database.table"""
cur.execute(query)
rows = cur.fetchall()
print(rows)

### Log output

ERROR: (builtins.NoneType) None [SQL: 'NoneType' object is not subscriptable] (Background on this error at:
https://sqlalche.me/e/14/dbapi)

### Operating System

macos

### Trino Python client version

4.0.0

### Trino Server version

442

### Python version

Python 3.10.4

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by vinayakmalik95** [comment] 2024-09-19 12:43
@ebyhr @hovaesco @hashhar 

Kindly allow to raise the PR for the same

**Comment by hashhar** [comment] 2024-09-19 14:38
Can you share full backtrace?

`if key in dict:` is idomatic python. The issue isn't that, the issue is `response` itself was probably `None`.

See example:

```python
>>> dict_with_key = {"k": "v"}
>>> dict_without_key = {"a": "v"}
>>> empty_dict = {}
>>> none_dict = None
>>>
>>> def check(d):
...     if "k" in d:
...             print("Exists")
...     else:
...             print("Does not exist")
...
>>> check(dict_with_key)
Exists
>>> check(dict_without_key)
Does not exist
>>> check(empty_dict)
Does not exist
>>> check(none_dict)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in check
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by hashhar** [comment] 2024-09-19 14:39
And this error doesn't match your error, so the cause is probably something else. Please share full backtrace so that we can identify the reason.

**Comment by hashhar** [comment] 2024-09-26 08:07
Closing for now since we are unable to reproduce this. Please feel free to reopen once you can share some steps to reproduce this (or at-least the full stack-trace).

**Closed by hashhar** 2024-09-26 08:07 UTC
