### ISSUE TITLE
Null "description" attribute in Cursor object failing dbapi2 compliancy check

### ISSUE THREAD

**Issue by KimberlyNgai** [trinodb/trino-python-client#450] opened 2024-02-14 19:29 UTC
We are using the Ray Data module using the read_sql method and underneath the hood, it is using a [check](https://github.com/ray-project/ray/blob/master/python/ray/data/datasource/sql_datasource.py#L35-L45) to make sure a cursor is dbapi2 compliant before using the cursor to execute a SQL query. However, the Trino client fails this check due to `description` being null. The [current Trino Cursor](https://github.com/trinodb/trino-python-client/blob/master/trino/dbapi.py#L376-L384) has description as null unless a query is executed first. 

Is it possible to have an empty list instead of NoneType?

**Comment by hashhar** [comment] 2024-02-16 11:21
it seems `hasattr` executes the `@property` which obviously returns `None`. If Ray Data module just needs to check for existence of `description` for example it should be using more generic mechanisms like `vars` or `dir`.

We don't default to an empty list because then people's existing scripts would break which depend on logic like - wait until description is available which is identified via `None`.

**Comment by hashhar** [comment] 2024-02-16 11:22
@przemekak is checking if there's something we can do here in the meantime.

For now to me it seems like Ray Data's checks need to be more generic.

**Comment by hashhar** [comment] 2024-02-16 11:41
oh actually seems it was fixed in https://github.com/trinodb/trino-python-client/pull/420.

The fix is not to lie about the return value. With the current code in master the `hasattr` check seems to pass for me.
I don't know how to use Ray Data so I can't test it with it but we plan to release a new version this week so you can try again once it's available.

Closing for now since most likely fixed.
Please re-open if you can still reproduce it with `0.328.0`.

**Closed by hashhar** 2024-02-16 11:41 UTC
